// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -412110152;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__simple__start_telemetry_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_telemetry_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::simple::VehicleSnapshot,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::simple::start_telemetry_stream(api_sink)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::simple::VehicleSnapshot,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::simple::MessageRateSnapshot> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::simple::MessageRateSnapshot>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::simple::MessageRateSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_messageType = <String>::sse_decode(deserializer);
        let mut var_count = <u32>::sse_decode(deserializer);
        let mut var_rateHz = <f32>::sse_decode(deserializer);
        let mut var_ageMs = <Option<u32>>::sse_decode(deserializer);
        return crate::api::simple::MessageRateSnapshot {
            message_type: var_messageType,
            count: var_count,
            rate_hz: var_rateHz,
            age_ms: var_ageMs,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u8>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::simple::VehicleSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_latitude = <Option<f64>>::sse_decode(deserializer);
        let mut var_longitude = <Option<f64>>::sse_decode(deserializer);
        let mut var_altitudeM = <Option<f32>>::sse_decode(deserializer);
        let mut var_rollDeg = <Option<f32>>::sse_decode(deserializer);
        let mut var_pitchDeg = <Option<f32>>::sse_decode(deserializer);
        let mut var_yawDeg = <Option<f32>>::sse_decode(deserializer);
        let mut var_batteryPct = <Option<u8>>::sse_decode(deserializer);
        let mut var_batteryVoltageV = <Option<f32>>::sse_decode(deserializer);
        let mut var_batteryCurrentA = <Option<f32>>::sse_decode(deserializer);
        let mut var_batteryValidity = <Option<String>>::sse_decode(deserializer);
        let mut var_batterySource = <Option<String>>::sse_decode(deserializer);
        let mut var_isArmed = <bool>::sse_decode(deserializer);
        let mut var_mode = <Option<String>>::sse_decode(deserializer);
        let mut var_gpsFixType = <Option<u8>>::sse_decode(deserializer);
        let mut var_satellitesVisible = <Option<u8>>::sse_decode(deserializer);
        let mut var_hdop = <Option<f32>>::sse_decode(deserializer);
        let mut var_heartbeatAgeS = <Option<f32>>::sse_decode(deserializer);
        let mut var_attitudeAgeS = <Option<f32>>::sse_decode(deserializer);
        let mut var_attitudeAgeMs = <Option<u32>>::sse_decode(deserializer);
        let mut var_positionAgeS = <Option<f32>>::sse_decode(deserializer);
        let mut var_batteryAgeS = <Option<f32>>::sse_decode(deserializer);
        let mut var_gpsAgeS = <Option<f32>>::sse_decode(deserializer);
        let mut var_vehicleSysid = <Option<u8>>::sse_decode(deserializer);
        let mut var_vehicleCompid = <Option<u8>>::sse_decode(deserializer);
        let mut var_yawSource = <Option<String>>::sse_decode(deserializer);
        let mut var_headingSource = <Option<String>>::sse_decode(deserializer);
        let mut var_lastMessageType = <Option<String>>::sse_decode(deserializer);
        let mut var_lockedVehicleSource = <bool>::sse_decode(deserializer);
        let mut var_messageRates =
            <Vec<crate::api::simple::MessageRateSnapshot>>::sse_decode(deserializer);
        let mut var_telemetrySourceType = <String>::sse_decode(deserializer);
        let mut var_telemetryBindAddress = <String>::sse_decode(deserializer);
        let mut var_telemetryPacketCount = <u32>::sse_decode(deserializer);
        let mut var_telemetryParseErrorCount = <u32>::sse_decode(deserializer);
        let mut var_telemetryMessageRateHz = <f32>::sse_decode(deserializer);
        let mut var_telemetryReceiveOnlyNote = <String>::sse_decode(deserializer);
        let mut var_statusText = <String>::sse_decode(deserializer);
        return crate::api::simple::VehicleSnapshot {
            latitude: var_latitude,
            longitude: var_longitude,
            altitude_m: var_altitudeM,
            roll_deg: var_rollDeg,
            pitch_deg: var_pitchDeg,
            yaw_deg: var_yawDeg,
            battery_pct: var_batteryPct,
            battery_voltage_v: var_batteryVoltageV,
            battery_current_a: var_batteryCurrentA,
            battery_validity: var_batteryValidity,
            battery_source: var_batterySource,
            is_armed: var_isArmed,
            mode: var_mode,
            gps_fix_type: var_gpsFixType,
            satellites_visible: var_satellitesVisible,
            hdop: var_hdop,
            heartbeat_age_s: var_heartbeatAgeS,
            attitude_age_s: var_attitudeAgeS,
            attitude_age_ms: var_attitudeAgeMs,
            position_age_s: var_positionAgeS,
            battery_age_s: var_batteryAgeS,
            gps_age_s: var_gpsAgeS,
            vehicle_sysid: var_vehicleSysid,
            vehicle_compid: var_vehicleCompid,
            yaw_source: var_yawSource,
            heading_source: var_headingSource,
            last_message_type: var_lastMessageType,
            locked_vehicle_source: var_lockedVehicleSource,
            message_rates: var_messageRates,
            telemetry_source_type: var_telemetrySourceType,
            telemetry_bind_address: var_telemetryBindAddress,
            telemetry_packet_count: var_telemetryPacketCount,
            telemetry_parse_error_count: var_telemetryParseErrorCount,
            telemetry_message_rate_hz: var_telemetryMessageRateHz,
            telemetry_receive_only_note: var_telemetryReceiveOnlyNote,
            status_text: var_statusText,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => {
            wire__crate__api__simple__start_telemetry_stream_impl(port, ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::MessageRateSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.message_type.into_into_dart().into_dart(),
            self.count.into_into_dart().into_dart(),
            self.rate_hz.into_into_dart().into_dart(),
            self.age_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::MessageRateSnapshot
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::MessageRateSnapshot>
    for crate::api::simple::MessageRateSnapshot
{
    fn into_into_dart(self) -> crate::api::simple::MessageRateSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::VehicleSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.latitude.into_into_dart().into_dart(),
            self.longitude.into_into_dart().into_dart(),
            self.altitude_m.into_into_dart().into_dart(),
            self.roll_deg.into_into_dart().into_dart(),
            self.pitch_deg.into_into_dart().into_dart(),
            self.yaw_deg.into_into_dart().into_dart(),
            self.battery_pct.into_into_dart().into_dart(),
            self.battery_voltage_v.into_into_dart().into_dart(),
            self.battery_current_a.into_into_dart().into_dart(),
            self.battery_validity.into_into_dart().into_dart(),
            self.battery_source.into_into_dart().into_dart(),
            self.is_armed.into_into_dart().into_dart(),
            self.mode.into_into_dart().into_dart(),
            self.gps_fix_type.into_into_dart().into_dart(),
            self.satellites_visible.into_into_dart().into_dart(),
            self.hdop.into_into_dart().into_dart(),
            self.heartbeat_age_s.into_into_dart().into_dart(),
            self.attitude_age_s.into_into_dart().into_dart(),
            self.attitude_age_ms.into_into_dart().into_dart(),
            self.position_age_s.into_into_dart().into_dart(),
            self.battery_age_s.into_into_dart().into_dart(),
            self.gps_age_s.into_into_dart().into_dart(),
            self.vehicle_sysid.into_into_dart().into_dart(),
            self.vehicle_compid.into_into_dart().into_dart(),
            self.yaw_source.into_into_dart().into_dart(),
            self.heading_source.into_into_dart().into_dart(),
            self.last_message_type.into_into_dart().into_dart(),
            self.locked_vehicle_source.into_into_dart().into_dart(),
            self.message_rates.into_into_dart().into_dart(),
            self.telemetry_source_type.into_into_dart().into_dart(),
            self.telemetry_bind_address.into_into_dart().into_dart(),
            self.telemetry_packet_count.into_into_dart().into_dart(),
            self.telemetry_parse_error_count
                .into_into_dart()
                .into_dart(),
            self.telemetry_message_rate_hz.into_into_dart().into_dart(),
            self.telemetry_receive_only_note
                .into_into_dart()
                .into_dart(),
            self.status_text.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::VehicleSnapshot
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::VehicleSnapshot>
    for crate::api::simple::VehicleSnapshot
{
    fn into_into_dart(self) -> crate::api::simple::VehicleSnapshot {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::simple::VehicleSnapshot,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::simple::MessageRateSnapshot> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::simple::MessageRateSnapshot>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::simple::MessageRateSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.message_type, serializer);
        <u32>::sse_encode(self.count, serializer);
        <f32>::sse_encode(self.rate_hz, serializer);
        <Option<u32>>::sse_encode(self.age_ms, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u8>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::simple::VehicleSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<f64>>::sse_encode(self.latitude, serializer);
        <Option<f64>>::sse_encode(self.longitude, serializer);
        <Option<f32>>::sse_encode(self.altitude_m, serializer);
        <Option<f32>>::sse_encode(self.roll_deg, serializer);
        <Option<f32>>::sse_encode(self.pitch_deg, serializer);
        <Option<f32>>::sse_encode(self.yaw_deg, serializer);
        <Option<u8>>::sse_encode(self.battery_pct, serializer);
        <Option<f32>>::sse_encode(self.battery_voltage_v, serializer);
        <Option<f32>>::sse_encode(self.battery_current_a, serializer);
        <Option<String>>::sse_encode(self.battery_validity, serializer);
        <Option<String>>::sse_encode(self.battery_source, serializer);
        <bool>::sse_encode(self.is_armed, serializer);
        <Option<String>>::sse_encode(self.mode, serializer);
        <Option<u8>>::sse_encode(self.gps_fix_type, serializer);
        <Option<u8>>::sse_encode(self.satellites_visible, serializer);
        <Option<f32>>::sse_encode(self.hdop, serializer);
        <Option<f32>>::sse_encode(self.heartbeat_age_s, serializer);
        <Option<f32>>::sse_encode(self.attitude_age_s, serializer);
        <Option<u32>>::sse_encode(self.attitude_age_ms, serializer);
        <Option<f32>>::sse_encode(self.position_age_s, serializer);
        <Option<f32>>::sse_encode(self.battery_age_s, serializer);
        <Option<f32>>::sse_encode(self.gps_age_s, serializer);
        <Option<u8>>::sse_encode(self.vehicle_sysid, serializer);
        <Option<u8>>::sse_encode(self.vehicle_compid, serializer);
        <Option<String>>::sse_encode(self.yaw_source, serializer);
        <Option<String>>::sse_encode(self.heading_source, serializer);
        <Option<String>>::sse_encode(self.last_message_type, serializer);
        <bool>::sse_encode(self.locked_vehicle_source, serializer);
        <Vec<crate::api::simple::MessageRateSnapshot>>::sse_encode(self.message_rates, serializer);
        <String>::sse_encode(self.telemetry_source_type, serializer);
        <String>::sse_encode(self.telemetry_bind_address, serializer);
        <u32>::sse_encode(self.telemetry_packet_count, serializer);
        <u32>::sse_encode(self.telemetry_parse_error_count, serializer);
        <f32>::sse_encode(self.telemetry_message_rate_hz, serializer);
        <String>::sse_encode(self.telemetry_receive_only_note, serializer);
        <String>::sse_encode(self.status_text, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
