// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -412110152;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_mavlink_gcs_portfolio',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<VehicleSnapshot> crateApiSimpleStartTelemetryStream();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<VehicleSnapshot> crateApiSimpleStartTelemetryStream() {
    final sink = RustStreamSink<VehicleSnapshot>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_vehicle_snapshot_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSimpleStartTelemetryStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleStartTelemetryStreamConstMeta =>
      const TaskConstMeta(
        debugName: "start_telemetry_stream",
        argNames: ["sink"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<VehicleSnapshot> dco_decode_StreamSink_vehicle_snapshot_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<MessageRateSnapshot> dco_decode_list_message_rate_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_message_rate_snapshot)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessageRateSnapshot dco_decode_message_rate_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MessageRateSnapshot(
      messageType: dco_decode_String(arr[0]),
      count: dco_decode_u_32(arr[1]),
      rateHz: dco_decode_f_32(arr[2]),
      ageMs: dco_decode_opt_box_autoadd_u_32(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VehicleSnapshot dco_decode_vehicle_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 36)
      throw Exception('unexpected arr length: expect 36 but see ${arr.length}');
    return VehicleSnapshot(
      latitude: dco_decode_opt_box_autoadd_f_64(arr[0]),
      longitude: dco_decode_opt_box_autoadd_f_64(arr[1]),
      altitudeM: dco_decode_opt_box_autoadd_f_32(arr[2]),
      rollDeg: dco_decode_opt_box_autoadd_f_32(arr[3]),
      pitchDeg: dco_decode_opt_box_autoadd_f_32(arr[4]),
      yawDeg: dco_decode_opt_box_autoadd_f_32(arr[5]),
      batteryPct: dco_decode_opt_box_autoadd_u_8(arr[6]),
      batteryVoltageV: dco_decode_opt_box_autoadd_f_32(arr[7]),
      batteryCurrentA: dco_decode_opt_box_autoadd_f_32(arr[8]),
      batteryValidity: dco_decode_opt_String(arr[9]),
      batterySource: dco_decode_opt_String(arr[10]),
      isArmed: dco_decode_bool(arr[11]),
      mode: dco_decode_opt_String(arr[12]),
      gpsFixType: dco_decode_opt_box_autoadd_u_8(arr[13]),
      satellitesVisible: dco_decode_opt_box_autoadd_u_8(arr[14]),
      hdop: dco_decode_opt_box_autoadd_f_32(arr[15]),
      heartbeatAgeS: dco_decode_opt_box_autoadd_f_32(arr[16]),
      attitudeAgeS: dco_decode_opt_box_autoadd_f_32(arr[17]),
      attitudeAgeMs: dco_decode_opt_box_autoadd_u_32(arr[18]),
      positionAgeS: dco_decode_opt_box_autoadd_f_32(arr[19]),
      batteryAgeS: dco_decode_opt_box_autoadd_f_32(arr[20]),
      gpsAgeS: dco_decode_opt_box_autoadd_f_32(arr[21]),
      vehicleSysid: dco_decode_opt_box_autoadd_u_8(arr[22]),
      vehicleCompid: dco_decode_opt_box_autoadd_u_8(arr[23]),
      yawSource: dco_decode_opt_String(arr[24]),
      headingSource: dco_decode_opt_String(arr[25]),
      lastMessageType: dco_decode_opt_String(arr[26]),
      lockedVehicleSource: dco_decode_bool(arr[27]),
      messageRates: dco_decode_list_message_rate_snapshot(arr[28]),
      telemetrySourceType: dco_decode_String(arr[29]),
      telemetryBindAddress: dco_decode_String(arr[30]),
      telemetryPacketCount: dco_decode_u_32(arr[31]),
      telemetryParseErrorCount: dco_decode_u_32(arr[32]),
      telemetryMessageRateHz: dco_decode_f_32(arr[33]),
      telemetryReceiveOnlyNote: dco_decode_String(arr[34]),
      statusText: dco_decode_String(arr[35]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<VehicleSnapshot> sse_decode_StreamSink_vehicle_snapshot_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<MessageRateSnapshot> sse_decode_list_message_rate_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageRateSnapshot>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_rate_snapshot(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessageRateSnapshot sse_decode_message_rate_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_messageType = sse_decode_String(deserializer);
    var var_count = sse_decode_u_32(deserializer);
    var var_rateHz = sse_decode_f_32(deserializer);
    var var_ageMs = sse_decode_opt_box_autoadd_u_32(deserializer);
    return MessageRateSnapshot(
      messageType: var_messageType,
      count: var_count,
      rateHz: var_rateHz,
      ageMs: var_ageMs,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VehicleSnapshot sse_decode_vehicle_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_latitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_longitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_altitudeM = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_rollDeg = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_pitchDeg = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_yawDeg = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_batteryPct = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_batteryVoltageV = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_batteryCurrentA = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_batteryValidity = sse_decode_opt_String(deserializer);
    var var_batterySource = sse_decode_opt_String(deserializer);
    var var_isArmed = sse_decode_bool(deserializer);
    var var_mode = sse_decode_opt_String(deserializer);
    var var_gpsFixType = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_satellitesVisible = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_hdop = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_heartbeatAgeS = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_attitudeAgeS = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_attitudeAgeMs = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_positionAgeS = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_batteryAgeS = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_gpsAgeS = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_vehicleSysid = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_vehicleCompid = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_yawSource = sse_decode_opt_String(deserializer);
    var var_headingSource = sse_decode_opt_String(deserializer);
    var var_lastMessageType = sse_decode_opt_String(deserializer);
    var var_lockedVehicleSource = sse_decode_bool(deserializer);
    var var_messageRates = sse_decode_list_message_rate_snapshot(deserializer);
    var var_telemetrySourceType = sse_decode_String(deserializer);
    var var_telemetryBindAddress = sse_decode_String(deserializer);
    var var_telemetryPacketCount = sse_decode_u_32(deserializer);
    var var_telemetryParseErrorCount = sse_decode_u_32(deserializer);
    var var_telemetryMessageRateHz = sse_decode_f_32(deserializer);
    var var_telemetryReceiveOnlyNote = sse_decode_String(deserializer);
    var var_statusText = sse_decode_String(deserializer);
    return VehicleSnapshot(
      latitude: var_latitude,
      longitude: var_longitude,
      altitudeM: var_altitudeM,
      rollDeg: var_rollDeg,
      pitchDeg: var_pitchDeg,
      yawDeg: var_yawDeg,
      batteryPct: var_batteryPct,
      batteryVoltageV: var_batteryVoltageV,
      batteryCurrentA: var_batteryCurrentA,
      batteryValidity: var_batteryValidity,
      batterySource: var_batterySource,
      isArmed: var_isArmed,
      mode: var_mode,
      gpsFixType: var_gpsFixType,
      satellitesVisible: var_satellitesVisible,
      hdop: var_hdop,
      heartbeatAgeS: var_heartbeatAgeS,
      attitudeAgeS: var_attitudeAgeS,
      attitudeAgeMs: var_attitudeAgeMs,
      positionAgeS: var_positionAgeS,
      batteryAgeS: var_batteryAgeS,
      gpsAgeS: var_gpsAgeS,
      vehicleSysid: var_vehicleSysid,
      vehicleCompid: var_vehicleCompid,
      yawSource: var_yawSource,
      headingSource: var_headingSource,
      lastMessageType: var_lastMessageType,
      lockedVehicleSource: var_lockedVehicleSource,
      messageRates: var_messageRates,
      telemetrySourceType: var_telemetrySourceType,
      telemetryBindAddress: var_telemetryBindAddress,
      telemetryPacketCount: var_telemetryPacketCount,
      telemetryParseErrorCount: var_telemetryParseErrorCount,
      telemetryMessageRateHz: var_telemetryMessageRateHz,
      telemetryReceiveOnlyNote: var_telemetryReceiveOnlyNote,
      statusText: var_statusText,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_vehicle_snapshot_Sse(
    RustStreamSink<VehicleSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_vehicle_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_message_rate_snapshot(
    List<MessageRateSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_rate_snapshot(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message_rate_snapshot(
    MessageRateSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.messageType, serializer);
    sse_encode_u_32(self.count, serializer);
    sse_encode_f_32(self.rateHz, serializer);
    sse_encode_opt_box_autoadd_u_32(self.ageMs, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vehicle_snapshot(
    VehicleSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_f_64(self.latitude, serializer);
    sse_encode_opt_box_autoadd_f_64(self.longitude, serializer);
    sse_encode_opt_box_autoadd_f_32(self.altitudeM, serializer);
    sse_encode_opt_box_autoadd_f_32(self.rollDeg, serializer);
    sse_encode_opt_box_autoadd_f_32(self.pitchDeg, serializer);
    sse_encode_opt_box_autoadd_f_32(self.yawDeg, serializer);
    sse_encode_opt_box_autoadd_u_8(self.batteryPct, serializer);
    sse_encode_opt_box_autoadd_f_32(self.batteryVoltageV, serializer);
    sse_encode_opt_box_autoadd_f_32(self.batteryCurrentA, serializer);
    sse_encode_opt_String(self.batteryValidity, serializer);
    sse_encode_opt_String(self.batterySource, serializer);
    sse_encode_bool(self.isArmed, serializer);
    sse_encode_opt_String(self.mode, serializer);
    sse_encode_opt_box_autoadd_u_8(self.gpsFixType, serializer);
    sse_encode_opt_box_autoadd_u_8(self.satellitesVisible, serializer);
    sse_encode_opt_box_autoadd_f_32(self.hdop, serializer);
    sse_encode_opt_box_autoadd_f_32(self.heartbeatAgeS, serializer);
    sse_encode_opt_box_autoadd_f_32(self.attitudeAgeS, serializer);
    sse_encode_opt_box_autoadd_u_32(self.attitudeAgeMs, serializer);
    sse_encode_opt_box_autoadd_f_32(self.positionAgeS, serializer);
    sse_encode_opt_box_autoadd_f_32(self.batteryAgeS, serializer);
    sse_encode_opt_box_autoadd_f_32(self.gpsAgeS, serializer);
    sse_encode_opt_box_autoadd_u_8(self.vehicleSysid, serializer);
    sse_encode_opt_box_autoadd_u_8(self.vehicleCompid, serializer);
    sse_encode_opt_String(self.yawSource, serializer);
    sse_encode_opt_String(self.headingSource, serializer);
    sse_encode_opt_String(self.lastMessageType, serializer);
    sse_encode_bool(self.lockedVehicleSource, serializer);
    sse_encode_list_message_rate_snapshot(self.messageRates, serializer);
    sse_encode_String(self.statusText, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
