// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `invalid_packet_snapshot`, `message_age_ms`, `message_rates_from_metadata`, `parse_telemetry_snapshot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AttitudePayload`, `FreshnessPayload`, `GpsPayload`, `HealthPayload`, `MotionPayload`, `PositionPayload`, `SourcePayload`, `SystemPayload`, `TelemetryMetadataPayload`, `TelemetryPayload`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Stream<VehicleSnapshot> startTelemetryStream() =>
    RustLib.instance.api.crateApiSimpleStartTelemetryStream();

class MessageRateSnapshot {
  final String messageType;
  final int count;
  final double rateHz;
  final int? ageMs;

  const MessageRateSnapshot({
    required this.messageType,
    required this.count,
    required this.rateHz,
    this.ageMs,
  });

  @override
  int get hashCode =>
      messageType.hashCode ^ count.hashCode ^ rateHz.hashCode ^ ageMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageRateSnapshot &&
          runtimeType == other.runtimeType &&
          messageType == other.messageType &&
          count == other.count &&
          rateHz == other.rateHz &&
          ageMs == other.ageMs;
}

class VehicleSnapshot {
  final double? latitude;
  final double? longitude;
  final double? altitudeM;
  final double? rollDeg;
  final double? pitchDeg;
  final double? yawDeg;
  final int? batteryPct;
  final double? batteryVoltageV;
  final double? batteryCurrentA;
  final String? batteryValidity;
  final String? batterySource;
  final bool isArmed;
  final String? mode;
  final int? gpsFixType;
  final int? satellitesVisible;
  final double? hdop;
  final double? heartbeatAgeS;
  final double? attitudeAgeS;
  final int? attitudeAgeMs;
  final double? positionAgeS;
  final double? batteryAgeS;
  final double? gpsAgeS;
  final int? vehicleSysid;
  final int? vehicleCompid;
  final String? yawSource;
  final String? headingSource;
  final String? lastMessageType;
  final bool lockedVehicleSource;
  final List<MessageRateSnapshot> messageRates;
  final String telemetrySourceType;
  final String telemetryBindAddress;
  final int telemetryPacketCount;
  final int telemetryParseErrorCount;
  final double telemetryMessageRateHz;
  final String telemetryReceiveOnlyNote;
  final String statusText;

  const VehicleSnapshot({
    this.latitude,
    this.longitude,
    this.altitudeM,
    this.rollDeg,
    this.pitchDeg,
    this.yawDeg,
    this.batteryPct,
    this.batteryVoltageV,
    this.batteryCurrentA,
    this.batteryValidity,
    this.batterySource,
    required this.isArmed,
    this.mode,
    this.gpsFixType,
    this.satellitesVisible,
    this.hdop,
    this.heartbeatAgeS,
    this.attitudeAgeS,
    this.attitudeAgeMs,
    this.positionAgeS,
    this.batteryAgeS,
    this.gpsAgeS,
    this.vehicleSysid,
    this.vehicleCompid,
    this.yawSource,
    this.headingSource,
    this.lastMessageType,
    required this.lockedVehicleSource,
    required this.messageRates,
    required this.telemetrySourceType,
    required this.telemetryBindAddress,
    required this.telemetryPacketCount,
    required this.telemetryParseErrorCount,
    required this.telemetryMessageRateHz,
    required this.telemetryReceiveOnlyNote,
    required this.statusText,
  });

  @override
  int get hashCode =>
      latitude.hashCode ^
      longitude.hashCode ^
      altitudeM.hashCode ^
      rollDeg.hashCode ^
      pitchDeg.hashCode ^
      yawDeg.hashCode ^
      batteryPct.hashCode ^
      batteryVoltageV.hashCode ^
      batteryCurrentA.hashCode ^
      batteryValidity.hashCode ^
      batterySource.hashCode ^
      isArmed.hashCode ^
      mode.hashCode ^
      gpsFixType.hashCode ^
      satellitesVisible.hashCode ^
      hdop.hashCode ^
      heartbeatAgeS.hashCode ^
      attitudeAgeS.hashCode ^
      attitudeAgeMs.hashCode ^
      positionAgeS.hashCode ^
      batteryAgeS.hashCode ^
      gpsAgeS.hashCode ^
      vehicleSysid.hashCode ^
      vehicleCompid.hashCode ^
      yawSource.hashCode ^
      headingSource.hashCode ^
      lastMessageType.hashCode ^
      lockedVehicleSource.hashCode ^
      messageRates.hashCode ^
      telemetrySourceType.hashCode ^
      telemetryBindAddress.hashCode ^
      telemetryPacketCount.hashCode ^
      telemetryParseErrorCount.hashCode ^
      telemetryMessageRateHz.hashCode ^
      telemetryReceiveOnlyNote.hashCode ^
      statusText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VehicleSnapshot &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          altitudeM == other.altitudeM &&
          rollDeg == other.rollDeg &&
          pitchDeg == other.pitchDeg &&
          yawDeg == other.yawDeg &&
          batteryPct == other.batteryPct &&
          batteryVoltageV == other.batteryVoltageV &&
          batteryCurrentA == other.batteryCurrentA &&
          batteryValidity == other.batteryValidity &&
          batterySource == other.batterySource &&
          isArmed == other.isArmed &&
          mode == other.mode &&
          gpsFixType == other.gpsFixType &&
          satellitesVisible == other.satellitesVisible &&
          hdop == other.hdop &&
          heartbeatAgeS == other.heartbeatAgeS &&
          attitudeAgeS == other.attitudeAgeS &&
          attitudeAgeMs == other.attitudeAgeMs &&
          positionAgeS == other.positionAgeS &&
          batteryAgeS == other.batteryAgeS &&
          gpsAgeS == other.gpsAgeS &&
          vehicleSysid == other.vehicleSysid &&
          vehicleCompid == other.vehicleCompid &&
          yawSource == other.yawSource &&
          headingSource == other.headingSource &&
          lastMessageType == other.lastMessageType &&
          lockedVehicleSource == other.lockedVehicleSource &&
          messageRates == other.messageRates &&
          telemetrySourceType == other.telemetrySourceType &&
          telemetryBindAddress == other.telemetryBindAddress &&
          telemetryPacketCount == other.telemetryPacketCount &&
          telemetryParseErrorCount == other.telemetryParseErrorCount &&
          telemetryMessageRateHz == other.telemetryMessageRateHz &&
          telemetryReceiveOnlyNote == other.telemetryReceiveOnlyNote &&
          statusText == other.statusText;
}
